version: '3.8'

services:
  myFoodApi:
    image: myfoodapi
    build:
      context: .
      dockerfile: myfood.Api/Api/Dockerfile
    
  myFood_db:
    image: postgres:alpine
  
volumes:
  myFood_db:

