global using Api.JwtConfiguration;
global using Api.Middleware;
global using Identity.Application;
global using Identity.infrastructure;
global using myfood.Messages.Extensions;
global using Notification;
global using Serilog;
global using Shared.Application;
global using Shared.Infrastructure;